140/host info
transparencia-mg/dpckan pull request #151
Opened 2022-02-01 22:46 UTC by gabrielbdornas

2022-02-04 20:31 UTC, gabrielbdornas commented
@fjuniorr inclui o issue #132 e #141 pois acredito que tenho uma sugestão de correção para os mesmo aqui. Criei os seguintes padrões de mensagem:

- Para o issue #141:
```
(venv) ➜  letters-datapackage git:(master) ✗ dpckan dataset update
Nothing to be updated in dataset: letters-vowel hosted in https://homologa.cge.mg.gov.br.
```
- Para o issue #132:
```
(venv) ➜  letters-datapackage git:(master) ✗ dpckan dataset update
Diff dataset letters-vowel error: 'resources_ids' not found in its 'extras' properties.
```

- Para update com sucesso:
```
(venv) ➜  letters-datapackage git:(master) ✗ dpckan dataset update
Updating dataset letters-vowel hosted in https://homologa.cge.mg.gov.br.
Updating resource letters-vowels data.
Updating resource datapackage.json.
Dataset letters-vowel updated.
```

2022-02-08 15:49 UTC, gabrielbdornas commented
> @gabrielbdornas a implementação atual somente faz atualização de recursos quando existe modificação nos arquivos de dados. Isso foi proposital?

@fjuniorr, foi proposital. Depois de nossa conversa na última semana a respeito das dificuldades de comparação entre metadados, inclusive gerando o issue #152, resolvi não realizar nenhuma comparação e deixar para discutir com você as possibilidades durante a nossa revisão do código. Duas opções:

* Atualizar somente o datapackage.json caso alguma diferença seja detectada neste;

* Usuário consciente deste tipo de modificação utiliza manualmente o `dpckan resource update` no datapackage.json.

2022-02-09 18:54 UTC, fjuniorr requested changes
## atualização dos metadados do datapackage.json (table schema, recurso ou dataset) não geram atualização

- [x] `resource_data_diff` está comparando somente dados

```
dpckan dataset create
dpckan dataset update
## Nothing to be updated in dataset: datapackage-reprex hosted in https://homologa.cge.mg.gov.br.
## change table schema
dpckan dataset update
## Nothing to be updated in dataset: datapackage-reprex hosted in https://homologa.cge.mg.gov.br.
```

## `dataset_patch` não precisa atualizar o pacote inteiro e pode ter nome mais específico

- [ ] `dataset_patch_resources_id`

http://docs.ckan.org/en/2.9/api/#ckan.logic.action.patch.package_patch

## melhorias das mensagens

- [x] No geral gostei bastante da revisão das mensagens. Algumas sugestões (URL é clickavel em alguns terminais)

- De: Diff dataset datapackage-reprex error: 'resources_ids' not found in its 'extras' properties.
- Para: 'resources_ids' property not found in 'extras' field of dataset https://homologa.cge.mg.gov.br/dataset/datapackage-reprex.

- De: Nothing to be updated in dataset: datapackage-reprex hosted in https://homologa.cge.mg.gov.br.
- Para: Nothing to be updated in dataset https://homologa.cge.mg.gov.br/dataset/datapackage-reprex.

- De: Updating dataset datapackage-reprex hosted in https://homologa.cge.mg.gov.br.
- Para: Updating dataset https://homologa.cge.mg.gov.br/dataset/datapackage-reprex

- De: Updating resource estados data.
- Para: Updating data files of resource estados...

2022-02-14 20:01 UTC, gabrielbdornas commented
Finalizado no PR #158

2022-02-14 20:01 UTC, closed without merging