140/host info backup
transparencia-mg/dpckan pull request #158
Opened 2022-02-14 19:56 UTC by gabrielbdornas

Observar conversa do PR que deu início a estas modificações - #151

2022-02-17 14:04 UTC, fjuniorr requested changes
Os metadados do recurso não estão sendo atualizados em `dpckan dataset update`. Para reproduzir:

- Crie um conjunto com `dpckan dataset create`
- Altere a propriedade `title` de um recurso qualquer
- Execute `dpckan dataset update`
- A mensagem "Updating resource <resource_name> metadata" vai aparecer, mas os metadados não são atualizados no CKAN

Se os dados do recurso são alterados, os metadados são atualizados. Eles também são atualizados em uma chamada explicita de `dpckan resource update`

2022-02-17 19:10 UTC, gabrielbdornas commented
> Os metadados do recurso não estão sendo atualizados em `dpckan dataset update`.

@fjuniorr, analiando a questão, descobri que a atualização de dados e matadados de um recurso estão dentro de uma mesma função `resource_update` (repare o dicionário payload):

```Python
def resource_update(ckan_instance, resource_id, resource):
  click.echo(f"Updating data and metadata of resource {resource.name}.")
  payload = {"id": resource_id,
             "name": resource.title,
             "description": resource.description,
             "url": resource.path}
  if(resource.path.startswith('http')):
    result = ckan_instance.call_action('resource_update', payload)
  else:
    result = ckan_instance.call_action('resource_update', payload, 
                                       files={'upload': open(os.path.join(resource.basepath, resource.path), 'rb')})
  return result
```
Como eu estava chamando esta função apenas no caso de divergência dos dados, os metadados não estavam sendo atualizados.

Não queria modificar isso neste momento pois agora estou muito receio dos efeitos adversos de cada mudança. Sendo assim, sugiro:
- Chamar as funções `resource_update` e `resource_update_datastore_metadata` sempre que uma diferença de dados **ou** metadados for identificada, resolvendo o problema paliativamente.
- Abrirmos um issue para realizar essa separação no futuro (após a inclusão de testes básicos do pacote), aonde teríamos uma função específica para atualização de dados, outra para metadados e outra para o datastore.

Por falar em datastore, também verifiquei que a chamada da API que realiza o update do datastore na verdade aponta para criação e não para atualização. Não me lembro se essa decisão no passado foi intencional e nem consegui idenficar se isso de fato é um problema, mas caso concorde com a abertura do issue proposto acima, poderíamos incluir o estudo para chamada de outros endpoints como o [upsert](http://docs.ckan.org/en/2.9/maintaining/datastore.html?highlight=datastore#ckanext.datastore.logic.action.datastore_upsert).

```
def resource_update_datastore_metadata(ckan_instance, resource_id, resource):
    ...
    ckan_instance.call_action('datastore_create', dataset_fields) 
```

Commitarei essa proposta aqui (#158) e caso concorde basta realizar o merge.

2022-02-17 22:12 UTC, fjuniorr commented
> @fjuniorr, analiando a questão, descobri que a atualização de dados e matadados de um recurso estão dentro de uma mesma função `resource_update` (repare o dicionário payload):
> 
> ```python
> def resource_update(ckan_instance, resource_id, resource):
>   click.echo(f"Updating data and metadata of resource {resource.name}.")
>   payload = {"id": resource_id,
>              "name": resource.title,
>              "description": resource.description,
>              "url": resource.path}
>   if(resource.path.startswith('http')):
>     result = ckan_instance.call_action('resource_update', payload)
>   else:
>     result = ckan_instance.call_action('resource_update', payload, 
>                                        files={'upload': open(os.path.join(resource.basepath, resource.path), 'rb')})
>   return result
> ```

Reparando no payload, a conversão de um recurso Frictionless para CKAN está acontecendo somente nesse snippet? Em caso positivo estamos perdendo metadados, como por exemplo `hash` que discutimos no https://github.com/transparencia-mg/dpckan/issues/155, que existe tanto no CKAN quanto na [spec da Frictionless](https://specs.frictionlessdata.io/data-resource/#metadata-properties). Se não tiver outra conversão em outra parte do código pode abrir um issue para melhorarmos a conversão no futuro.


> Por falar em datastore, também verifiquei que a chamada da API que realiza o update do datastore na verdade aponta para criação e não para atualização. Não me lembro se essa decisão no passado foi intencional e nem consegui idenficar se isso de fato é um problema, mas caso concorde com a abertura do issue proposto acima, poderíamos incluir o estudo para chamada de outros endpoints como o [upsert](http://docs.ckan.org/en/2.9/maintaining/datastore.html?highlight=datastore#ckanext.datastore.logic.action.datastore_upsert).

Acho que foi intencional sim pq o [upsert](https://docs.ckan.org/en/2.9/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_upsert) não consegue fazer a atualização do [dicionário de dados](https://docs.ckan.org/en/2.9/maintaining/datastore.html#fields), a única coisa que atualizamos via API. Os dados em si são inseridos pelo Datapusher. Talvez fazer a carga dos dados também, usando o argumento `records` nos endpoints pode ser uma solução para https://github.com/transparencia-mg/dpckan/issues/41, desde que o volume de dados não seja muito grande.

2022-02-18 13:24 UTC, gabrielbdornas commented on dpckan/functions.py
> +        resource_update_datastore_metadata(ckan_instance, resource['id'], datapackage.get_resource(resource['name']))
Perfeito. Implementado [aqui](https://github.com/transparencia-mg/dpckan/pull/158/commits/2df6e891bce7025048adf6771a25a760a7351093).

2022-02-18 13:31 UTC, gabrielbdornas commented
> Reparando no payload, a conversão de um recurso Frictionless para CKAN está acontecendo somente nesse snippet? Em caso positivo estamos perdendo metadados, como por exemplo `hash` que discutimos no #155, que existe tanto no CKAN quanto na [spec da Frictionless](https://specs.frictionlessdata.io/data-resource/#metadata-properties). Se não tiver outra conversão em outra parte do código pode abrir um issue para melhorarmos a conversão no futuro.

O único lugar que a conversão acontece para recursos é no payload sim. Dentro da função `frictionless_to_ckan` os recursos são excluídos da conversão (linha 242) abaixo.

https://github.com/transparencia-mg/dpckan/blob/2df6e891bce7025048adf6771a25a760a7351093/dpckan/functions.py#L240-L257

Posso estar confundindo, mas acredito que essa conversa tem relação com o #81. Se estiver correto, podemos melhorar este issue, ao invés de criar outro. o que acha @fjuniorr

2022-02-18 14:52 UTC, fjuniorr commented
> Posso estar confundindo, mas acredito que essa conversa tem relação com o #81. Se estiver correto, podemos melhorar este issue, ao invés de criar outro. o que acha @fjuniorr

Não lembrava desse issue! Podemos atacar isso nele sim.

2022-02-18 14:54 UTC, fjuniorr approved these changes

2022-02-18 18:14 UTC, fjuniorr commented
LGTM :+1:

2022-02-18 18:15 UTC, merged